### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by longfangsong** [longfangsong/autoAPI#1]
yaml examples:
Naive table:
```yaml
dbengin: pgsql
tablename: test
fields:
  - name: id
    type: int
  - name: name
    type: string
```
Auto decide everything it can from meta tables
```yaml
dbengin: pgsql
tablename: test
```
